[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dfode"
version = "0.1"
dependencies = [
    "numpy",
    "cantera>=3.2.0",
    "h5py",
    "matplotlib",
    "PyYAML",
    "torch",
]

[project.optional-dependencies]
dev = [
    "pytest",
]
hit = [
    "nslab2d @ git+https://github.com/xiao312/NS2dLab_Python.git",
]

[project.scripts]
dfode-kit = "dfode_kit.cli.main:main"

[tool.setuptools.packages.find]
include = ["dfode_kit*"]
