from __future__ import annotations

import json


def add_command_parser(subparsers):
    parser = subparsers.add_parser(
        "export-hit-openfoam-u",
        help="Export a designed 2D HIT velocity field to an OpenFOAM U file.",
    )
    parser.add_argument("--field-npz", required=True, help="Velocity field .npz generated by design-hit-flame-case.")
    parser.add_argument("--case-dir", required=True, help="Target OpenFOAM case directory.")
    parser.add_argument("--time-dir", default="0", help="OpenFOAM time directory to write into.")
    parser.add_argument("--ordering", choices=("x-fastest", "y-fastest"), default="x-fastest", help="Structured-cell flattening order.")
    parser.add_argument("--boundary-json", default=None, help="Optional JSON boundaryField patch dictionary.")


def handle_command(args):
    from dfode_kit.cfd_init.hit2d import export_hit_openfoam_u

    path = export_hit_openfoam_u(
        field_npz=args.field_npz,
        case_dir=args.case_dir,
        time_dir=args.time_dir,
        ordering=args.ordering,
        boundary_json=args.boundary_json,
    )
    print(json.dumps({"path": str(path)}, indent=2, sort_keys=True))
