#!/bin/bash
set -euo pipefail

: "${DFODE_PROJECT_ROOT:?Set DFODE_PROJECT_ROOT}"
: "${DFODE_CASE_FILE:?Set DFODE_CASE_FILE}"
: "${DFODE_DATA_FILE:?Set DFODE_DATA_FILE}"
: "${DFODE_SPECIES_FILE:?Set DFODE_SPECIES_FILE}"
: "${DFODE_EXPORT_CONFIG:?Set DFODE_EXPORT_CONFIG}"
: "${DFODE_MECHANISM:?Set DFODE_MECHANISM}"

SOURCE_ROOT="${DFODE_SOURCE_ROOT:-${DFODE_PROJECT_ROOT}/.work/src/DFODE-kit}"
DCU_PYTHON="${DFODE_PYTHON:-${DFODE_PROJECT_ROOT}/.work/envs/dtk2604-torch251-py311/bin/python}"
RUN_ID="${DFODE_RUN_ID:-$(date +%y%m%d)_sandia_xiao_perturb_r192}"
PIPELINE_ROOT="${DFODE_PIPELINE_ROOT:-${DFODE_PROJECT_ROOT}/.work/pipelines/${RUN_ID}}"
DATA_ROOT="${PIPELINE_ROOT}/data"
TRAIN_ROOT="${PIPELINE_ROOT}/training"
mkdir -p "${DATA_ROOT}" "${TRAIN_ROOT}" "${DFODE_PROJECT_ROOT}/.work/logs"

TRAIN_SOURCE="${DATA_ROOT}/train-pairs.h5"
VALIDATION_SOURCE="${DATA_ROOT}/validation-pairs.h5"
TEST_SOURCE="${DATA_ROOT}/test-pairs.h5"
CHECKPOINT="${TRAIN_ROOT}/checkpoint.pt"
COMMON_EXPORT="ALL,REPO_ROOT=${SOURCE_ROOT},PLUGS_ROOT=${DFODE_PROJECT_ROOT},PIPELINE_DIR=${PIPELINE_ROOT},DFODE_DCU_PYTHON=${DCU_PYTHON},CASE_FILE=${DFODE_CASE_FILE},DATA_FILE=${DFODE_DATA_FILE},SPECIES_FILE=${DFODE_SPECIES_FILE},SNAPSHOT_CONFIG=${DFODE_EXPORT_CONFIG},DFODE_MECHANISM=${DFODE_MECHANISM}"

DATA_JOB="$(
    sbatch --parsable \
        --cpus-per-task=32 \
        --mem=64G \
        --time=24:00:00 \
        --export="${COMMON_EXPORT},DFODE_PERTURBATION_ROUNDS=${DFODE_PERTURBATION_ROUNDS:-192},DFODE_DATA_SHARDS=${DFODE_SHARDS:-32},DFODE_DATA_PARALLEL_JOBS=${DFODE_PARALLEL_JOBS:-32},DFODE_SEED=${DFODE_SEED:-260624}" \
        "${SOURCE_ROOT}/platforms/scnet/slurm/run_cfd_perturb_data.slurm"
)"

TRAIN_JOB="$(
    sbatch --parsable \
        --nodes="${DFODE_TRAIN_NODES:-2}" \
        --dependency="afterok:${DATA_JOB}" \
        --export="ALL,DFODE_PROJECT_ROOT=${DFODE_PROJECT_ROOT},DFODE_SOURCE_ROOT=${SOURCE_ROOT},DFODE_TRAIN_SOURCE=${TRAIN_SOURCE},DFODE_VALIDATION_SOURCE=${VALIDATION_SOURCE},DFODE_MECHANISM=${DFODE_MECHANISM},DFODE_CHECKPOINT=${CHECKPOINT},DFODE_EPOCHS=${DFODE_EPOCHS:-2000},DFODE_BATCH_SIZE_PER_DEVICE=${DFODE_BATCH_SIZE_PER_DEVICE:-512},DFODE_LEARNING_RATE=${DFODE_LEARNING_RATE:-1e-3},DFODE_MINIMUM_LEARNING_RATE=${DFODE_MINIMUM_LEARNING_RATE:-1e-5},DFODE_DCU_COUNT=4,DFODE_SEED=${DFODE_SEED:-260624}" \
        "${SOURCE_ROOT}/platforms/scnet/slurm/run_cfd_perturb_distributed_train.slurm"
)"

GATE_JOB="$(
    sbatch --parsable \
        --dependency="afterok:${TRAIN_JOB}" \
        --export="${COMMON_EXPORT},TRAIN_RUN_DIR=${TRAIN_ROOT}" \
        "${SOURCE_ROOT}/platforms/scnet/slurm/run_cfd_perturb_gate.slurm"
)"

cat <<EOF
pipeline_root=${PIPELINE_ROOT}
data_job=${DATA_JOB}
training_job=${TRAIN_JOB}
gate_job=${GATE_JOB}
train_source=${TRAIN_SOURCE}
validation_source=${VALIDATION_SOURCE}
test_source=${TEST_SOURCE}
best_checkpoint=${CHECKPOINT}
EOF
